import RootLayout from '@/components/layouts'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Maruf Hossain',
  description: 'Generated by create next app',
  icons: ["/brand.png"]
}

export default function RootLayoutPage({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <RootLayout>
          {children}
        </RootLayout>
      </body>
    </html>
  )
}
